@extends('admin.layouts.app')
@section('title','Dashboard')
@section('page_title','Visão geral')
@section('content')
<div class="row g-3 mb-4">@foreach($cards as $card)<div class="col-6 col-xl-3"><a href="{{ route('admin.resources.index',$card['resource']) }}" class="text-decoration-none"><div class="card metric-card h-100"><div class="card-body d-flex align-items-center gap-3"><div class="metric-icon"><i class="bi bi-{{ $card['icon'] }}"></i></div><div><div class="text-secondary small">{{ $card['label'] }}</div><div class="h3 mb-0 text-dark">{{ number_format($card['value'],0,',','.') }}</div></div></div></div></a></div>@endforeach</div>
<div class="row g-3 mb-4"><div class="col-lg-6"><div class="card metric-card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><small class="text-secondary">Fila database</small><div class="h4 mb-0">{{ $pendingDatabaseJobs }} pendentes</div></div><i class="bi bi-stack fs-3 text-primary"></i></div></div></div></div><div class="col-lg-6"><div class="card metric-card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><small class="text-secondary">Falhas de fila</small><div class="h4 mb-0">{{ $failedJobs }} registradas</div></div><i class="bi bi-exclamation-triangle fs-3 text-danger"></i></div></div></div></div></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Monitoramento operacional</h2><a href="{{ route('admin.monitoring.index') }}" class="btn btn-dark btn-sm">Abrir central</a></div>
<div class="row g-3"><div class="col-xl-4"><div class="card table-card h-100"><div class="card-header bg-white fw-semibold py-3">Últimos usuários</div><div class="list-group list-group-flush">@forelse($recentUsers as $u)<a class="list-group-item list-group-item-action" href="{{ route('admin.resources.show',['users',$u->id]) }}"><strong>{{ $u->name }} {{ $u->last_name }}</strong><div class="small text-secondary">{{ $u->email }}</div></a>@empty<div class="p-4 text-secondary">Nenhum usuário.</div>@endforelse</div></div></div><div class="col-xl-4"><div class="card table-card h-100"><div class="card-header bg-white fw-semibold py-3">Currículos recentes</div><div class="list-group list-group-flush">@forelse($recentResumes as $r)<a class="list-group-item list-group-item-action" href="{{ route('admin.resources.show',['user-resumes',$r->id]) }}"><strong>{{ $r->name }}</strong><div class="small text-secondary">{{ $r->user?->email }} · {{ $r->status->value ?? $r->status }}</div></a>@empty<div class="p-4 text-secondary">Nenhum currículo.</div>@endforelse</div></div></div><div class="col-xl-4"><div class="card table-card h-100"><div class="card-header bg-white fw-semibold py-3">Candidaturas recentes</div><div class="list-group list-group-flush">@forelse($recentApplications as $a)<a class="list-group-item list-group-item-action" href="{{ route('admin.resources.show',['job-applications',$a->id]) }}"><strong>{{ $a->jobPosting?->title ?? 'Vaga #'.$a->job_posting_id }}</strong><div class="small text-secondary">{{ $a->user?->email }} · {{ $a->status }}</div></a>@empty<div class="p-4 text-secondary">Nenhuma candidatura.</div>@endforelse</div></div></div></div>
@endsection
