@extends('admin.layouts.app')
@section('title','Monitoramento')
@section('page_title','Monitoramento')
@section('content')
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card metric-card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><small class="text-secondary">Redis</small><div class="h5 mb-1">{{ $redis['ok']?'Online':'Offline' }}</div><small class="{{ $redis['ok']?'text-success':'text-danger' }}">{{ \Illuminate\Support\Str::limit($redis['message'],80) }}</small></div><i class="bi bi-database-check fs-2 {{ $redis['ok']?'text-success':'text-danger' }}"></i></div></div></div></div><div class="col-md-4"><div class="card metric-card h-100"><div class="card-body"><small class="text-secondary">Conexão de filas</small><div class="h5 mb-1">{{ $queueConnection }}</div><small class="text-secondary">Horizon exige Redis.</small></div></div></div><div class="col-md-4"><div class="card metric-card h-100"><div class="card-body"><small class="text-secondary">Ferramentas</small><div class="d-flex gap-2 mt-2"><span class="badge {{ $pulseInstalled?'text-bg-success':'text-bg-warning' }}">Pulse {{ $pulseInstalled?'OK':'pendente' }}</span><span class="badge {{ $horizonInstalled?'text-bg-success':'text-bg-warning' }}">Horizon {{ $horizonInstalled?'OK':'pendente' }}</span></div></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-lg-6"><div class="card form-card h-100"><div class="card-body p-4"><h2 class="h5">Laravel Pulse</h2><p class="text-secondary">Desempenho da aplicação, requisições lentas, queries, exceções, servidores e uso.</p><a href="/pulse" target="_blank" class="btn btn-primary">Abrir Pulse <i class="bi bi-box-arrow-up-right ms-1"></i></a></div></div></div><div class="col-lg-6"><div class="card form-card h-100"><div class="card-body p-4"><h2 class="h5">Laravel Horizon</h2><p class="text-secondary">Throughput, duração, filas Redis, jobs falhos e supervisores.</p><a href="/horizon" target="_blank" class="btn btn-dark">Abrir Horizon <i class="bi bi-box-arrow-up-right ms-1"></i></a></div></div></div></div>
<div class="card table-card mb-4"><div class="card-header bg-white py-3 fw-semibold">Jobs falhos recentes</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>UUID</th><th>Conexão</th><th>Fila</th><th>Falhou em</th><th class="text-end">Ações</th></tr></thead><tbody>@forelse($failedJobs as $job)<tr><td><code>{{ \Illuminate\Support\Str::limit($job->uuid,24) }}</code></td><td>{{ $job->connection }}</td><td>{{ $job->queue }}</td><td>{{ $job->failed_at }}</td><td class="text-end"><form class="d-inline" method="POST" action="{{ route('admin.monitoring.failed.retry',$job->uuid) }}">@csrf<button class="btn btn-sm btn-outline-primary">Reprocessar</button></form><form class="d-inline" method="POST" action="{{ route('admin.monitoring.failed.forget',$job->uuid) }}" data-confirm-delete="Remover este job falho?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remover</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Nenhum job falho registrado.</td></tr>@endforelse</tbody></table></div></div>
<div class="card table-card"><div class="card-header bg-white py-3 fw-semibold">Fila database (legado/fallback)</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ID</th><th>Fila</th><th>Tentativas</th><th>Disponível</th></tr></thead><tbody>@forelse($databaseJobs as $job)<tr><td>{{ $job->id }}</td><td>{{ $job->queue }}</td><td>{{ $job->attempts }}</td><td>{{ date('d/m/Y H:i:s',$job->available_at) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">Nenhum job no driver database.</td></tr>@endforelse</tbody></table></div></div>
@endsection
