import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { useAuth } from "@/features/auth/context/auth-context";
import { getDashboard } from "@/features/platform/services/platform-service";
import type { DashboardData } from "@/features/platform/types/data";

export default function DashboardScreen(){
 const {token,user}=useAuth();const router=useRouter();const [data,setData]=useState<DashboardData|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{if(!token)return;try{setData(await getDashboard(token))}finally{setLoading(false);setRefreshing(false)}},[token]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 if(loading)return <View style={s.center}><ActivityIndicator color="#8B6CFF"/></View>;
 const stats=data?.statistics;
 return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}} tintColor="#8B6CFF"/>}>
  <Text style={s.hello}>Olá, {user?.name ?? ""}</Text><Text style={s.title}>Seu Talora Apply</Text><Text style={s.sub}>Informações reais da sua conta e das oportunidades cadastradas.</Text>
  {data?.primary_resume?<View style={s.runtimeInfo}><Ionicons name="refresh-circle-outline" size={20} color="#9B84FF"/><Text style={s.runtimeText}>Compatibilidade calculada agora com <Text style={s.runtimeStrong}>{data.primary_resume.name}</Text>. Trocar o principal reavalia as vagas.</Text></View>:<Pressable onPress={()=>router.push('/resumes' as never)} style={s.runtimeWarning}><Ionicons name="alert-circle-outline" size={20} color="#F8C15C"/><Text style={s.warningText}>Escolha um currículo processado como principal para calcular compatibilidade.</Text></Pressable>}
  <View style={s.grid}><Stat icon="briefcase-outline" label="Vagas" value={String(stats?.jobs_found??0)}/><Stat icon="analytics-outline" label="Compatibilidade" value={stats?.average_compatibility==null?"—":`${stats.average_compatibility}%`}/><Stat icon="send-outline" label="Candidaturas" value={String(stats?.applications??0)}/><Stat icon="heart-outline" label="Favoritas" value={String(stats?.favorites??0)}/></View>
  <View style={s.sectionHead}><Text style={s.sectionTitle}>Oportunidades recentes</Text><Pressable onPress={()=>router.push("/explore" as never)}><Text style={s.link}>Ver todas</Text></Pressable></View>
  {data?.opportunities?.length?data.opportunities.map(j=><Pressable key={j.id} onPress={()=>router.push("/explore" as never)} style={s.card}><View style={s.jobIcon}><Text style={s.jobInitial}>{(j.company?.name??"?").slice(0,2).toUpperCase()}</Text></View><View style={s.flex}><Text style={s.jobTitle}>{j.title}</Text><Text style={s.meta}>{j.company?.name??"Empresa não informada"}{j.location?` · ${j.location}`:""}</Text></View><Text style={s.score}>{j.compatibility_score==null?"—":`${j.compatibility_score}%`}</Text></Pressable>):<Empty text="Nenhuma vaga ativa cadastrada."/>}
  <Text style={[s.sectionTitle,{marginTop:24}]}>Análise do currículo principal</Text>{data?.resume_analysis?<View style={s.analysis}><Row l="Título" v={data.resume_analysis.professional_title??"Não identificado"}/><Row l="Senioridade" v={data.resume_analysis.seniority_level??"Não identificada"}/>{data.resume_analysis.overall_score!=null?<Row l="Score geral" v={`${data.resume_analysis.overall_score}%`}/>:null}{data.resume_analysis.ats_score!=null?<Row l="ATS" v={`${data.resume_analysis.ats_score}%`}/>:null}</View>:<Empty text="Nenhuma análise do currículo principal concluída ainda."/>}
 </ScrollView>
}
function Stat({icon,label,value}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string}){return <View style={s.stat}><Ionicons name={icon} size={21} color="#9B84FF"/><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
function Row({l,v}:{l:string;v:string}){return <View style={s.row}><Text style={s.rowL}>{l}</Text><Text style={s.rowV}>{v}</Text></View>}
function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.emptyText}>{text}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0B1020'},content:{padding:20,paddingBottom:110},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0B1020'},hello:{color:'#15D0A5',fontSize:13,fontWeight:'800'},title:{color:'#F8FAFC',fontSize:28,fontWeight:'900',marginTop:5},sub:{color:'#94A3B8',marginTop:8,lineHeight:20},runtimeInfo:{flexDirection:'row',gap:9,alignItems:'flex-start',borderWidth:1,borderColor:'rgba(109,74,255,.35)',backgroundColor:'rgba(109,74,255,.10)',borderRadius:16,padding:14,marginTop:18},runtimeText:{color:'#CBD5E1',fontSize:12,lineHeight:18,flex:1},runtimeStrong:{color:'#F8FAFC',fontWeight:'800'},runtimeWarning:{flexDirection:'row',gap:9,alignItems:'flex-start',borderWidth:1,borderColor:'rgba(248,193,92,.35)',backgroundColor:'rgba(248,193,92,.10)',borderRadius:16,padding:14,marginTop:18},warningText:{color:'#FDE7B3',fontSize:12,lineHeight:18,flex:1},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:22},stat:{width:'48%',borderWidth:1,borderColor:'#1E293B',backgroundColor:'#161C2D',borderRadius:18,padding:16},statValue:{color:'#F8FAFC',fontSize:25,fontWeight:'900',marginTop:10},statLabel:{color:'#94A3B8',fontSize:12,marginTop:3},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:26,marginBottom:10},sectionTitle:{color:'#F8FAFC',fontSize:18,fontWeight:'800'},link:{color:'#15D0A5',fontWeight:'700'},card:{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#1E293B',backgroundColor:'#161C2D',borderRadius:18,padding:14,marginBottom:9},jobIcon:{width:44,height:44,borderRadius:12,backgroundColor:'rgba(109,74,255,.15)',alignItems:'center',justifyContent:'center'},jobInitial:{color:'#B9ABFF',fontWeight:'900'},flex:{flex:1},jobTitle:{color:'#F8FAFC',fontWeight:'800'},meta:{color:'#64748B',fontSize:11,marginTop:4},score:{color:'#15D0A5',fontWeight:'900'},analysis:{borderWidth:1,borderColor:'#1E293B',backgroundColor:'#161C2D',borderRadius:18,padding:16,marginTop:10},row:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#1E293B'},rowL:{color:'#64748B'},rowV:{color:'#F8FAFC',fontWeight:'700',flex:1,textAlign:'right'},empty:{borderWidth:1,borderStyle:'dashed',borderColor:'#334155',borderRadius:16,padding:20,marginTop:10},emptyText:{color:'#64748B',textAlign:'center'}})
