import * as DocumentPicker from "expo-document-picker";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { EmptyCard, SectionScreen } from "@/components/platform/section-screen";
import { useAuth } from "@/features/auth/context/auth-context";
import { getResumes, setPrimaryResume, uploadResume } from "@/features/resumes/services/resume-service";
import type { UserResume } from "@/features/resumes/types/resume";
import { useToast } from "@/components/feedback/toast-provider";

const statusLabel: Record<string,string>={pending:'Na fila',processing:'Processando',completed:'Analisado',failed:'Falhou'};
function bytes(value:number){return `${(value/1024/1024).toFixed(2)} MB`;}

export default function ResumesScreen(){
 const router=useRouter(); const {token,refreshResumeState}=useAuth(); const toast=useToast(); const [resumes,setResumes]=useState<UserResume[]>([]); const [loading,setLoading]=useState(true); const [uploading,setUploading]=useState(false); const [changingPrimary,setChangingPrimary]=useState<number|null>(null); const [error,setError]=useState<string|null>(null);
 async function load(){if(!token)return;setLoading(true);try{setResumes(await getResumes(token));setError(null);}catch{setError('Não foi possível carregar seus currículos.');}finally{setLoading(false)}}
 useEffect(()=>{void load()},[token]);
 async function addResume(){if(!token)return;const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],multiple:false,copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];if(!asset)return;setUploading(true);setError(null);try{await uploadResume({token,file:{uri:asset.uri,name:asset.name,mimeType:asset.mimeType},name:asset.name.replace(/\.[^.]+$/,'')});await refreshResumeState();await load();toast.success('Currículo enviado e adicionado à fila de processamento.');}catch{setError('Não foi possível enviar o currículo.');}finally{setUploading(false)}}
 async function choosePrimary(id:number){if(!token)return;setChangingPrimary(id);setError(null);try{await setPrimaryResume(token,id);await refreshResumeState();await load();toast.success('Currículo principal alterado. As vagas serão reavaliadas com este CV.');}catch{setError('Não foi possível alterar o currículo principal.');}finally{setChangingPrimary(null)}}
 const hasCompleted=resumes.some(r=>r.status==='completed'); const hasPrimary=resumes.some(r=>r.is_primary);
 return <SectionScreen title="Meus currículos" subtitle="Escolha qual CV processado deve ser usado nas comparações com vagas." icon="document-text-outline">
  {!hasPrimary&&hasCompleted?<View style={styles.notice}><Ionicons name="alert-circle-outline" size={19} color="#F8C15C"/><Text style={styles.noticeText}>Escolha um currículo principal para habilitar a compatibilidade dinâmica.</Text></View>:null}
  {loading?<ActivityIndicator color="#8B6CFF"/>:resumes.length===0?<EmptyCard title="Nenhum currículo enviado" text="Envie seu primeiro CV para iniciar o processamento."/>:resumes.map(r=><View key={r.id} style={styles.card}><View style={styles.row}><Ionicons name="document-text-outline" size={24} color="#9B84FF"/><View style={styles.flex}><View style={styles.nameRow}><Text style={styles.name}>{r.name}</Text>{r.is_primary?<Text style={styles.primary}>Principal</Text>:null}</View><Text style={styles.meta}>{r.original_filename} · {bytes(r.size)}</Text><Text style={styles.status}>{statusLabel[r.status]??r.status}{r.ats_friendly===true?' · ATS friendly':''}</Text></View></View><View style={styles.actions}>{r.status==='completed'&&!r.is_primary?<Pressable disabled={changingPrimary===r.id} onPress={()=>void choosePrimary(r.id)} style={styles.primaryButton}>{changingPrimary===r.id?<ActivityIndicator color="#B9ABFF" size="small"/>:<><Ionicons name="star-outline" size={16} color="#B9ABFF"/><Text style={styles.primaryButtonText}>Definir como principal</Text></>}</Pressable>:null}<Pressable onPress={()=>router.push(`/resumes/${r.id}` as never)} style={styles.detail}><Text style={styles.detailText}>Ver detalhes</Text><Ionicons name="chevron-forward" size={17} color="#FFF"/></Pressable></View></View>)}
  {error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={uploading} onPress={()=>void addResume()} style={styles.button}>{uploading?<ActivityIndicator color="#FFF"/>:<><Ionicons name="add" size={20} color="#FFF"/><Text style={styles.buttonText}>Enviar novo currículo</Text></>}</Pressable>
 </SectionScreen>;
}
const styles=StyleSheet.create({notice:{flexDirection:'row',gap:9,alignItems:'flex-start',borderWidth:1,borderColor:'rgba(248,193,92,.35)',backgroundColor:'rgba(248,193,92,.10)',borderRadius:16,padding:14,marginBottom:12},noticeText:{color:'#FDE7B3',fontSize:12,lineHeight:18,flex:1},card:{borderWidth:1,borderColor:'#1E293B',backgroundColor:'#161C2D',borderRadius:18,padding:16,marginBottom:10},row:{flexDirection:'row',gap:12,alignItems:'center'},flex:{flex:1},nameRow:{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'},name:{color:'#F8FAFC',fontWeight:'800'},primary:{color:'#4BE3BF',fontSize:10,fontWeight:'800',backgroundColor:'rgba(21,208,165,.10)',paddingHorizontal:7,paddingVertical:3,borderRadius:999},meta:{color:'#64748B',fontSize:11,marginTop:5},status:{color:'#94A3B8',fontSize:11,marginTop:5},actions:{marginTop:14,gap:8},primaryButton:{minHeight:42,borderRadius:12,borderWidth:1,borderColor:'rgba(109,74,255,.45)',backgroundColor:'rgba(109,74,255,.10)',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6},primaryButtonText:{color:'#B9ABFF',fontSize:12,fontWeight:'800'},detail:{minHeight:42,borderRadius:12,backgroundColor:'#6D4AFF',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},detailText:{color:'#FFF',fontSize:12,fontWeight:'800'},button:{minHeight:50,borderRadius:14,backgroundColor:'#6D4AFF',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:8},buttonText:{color:'#FFF',fontWeight:'800'},error:{color:'#FDA4AF',fontSize:12,marginVertical:10}})
