import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SectionScreen } from "@/components/platform/section-screen";
import { useAuth } from "@/features/auth/context/auth-context";
import { updatePassword, updateProfile } from "@/features/account/services/account-service";
import { useToast } from "@/components/feedback/toast-provider";

export default function SettingsScreen(){
 const {user,token,refreshUser}=useAuth(); const toast=useToast(); const [name,setName]=useState(user?.name??''); const [lastName,setLastName]=useState(user?.last_name??''); const [saving,setSaving]=useState(false); const [current,setCurrent]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [changing,setChanging]=useState(false);
 async function saveProfile(){if(!token)return;if(name.trim().length<2||lastName.trim().length<2)return Alert.alert('Atenção','Preencha nome e sobrenome corretamente.');setSaving(true);try{await updateProfile(token,{name:name.trim(),last_name:lastName.trim()});await refreshUser();toast.success('Dados atualizados com sucesso.');}catch(e){Alert.alert('Erro',e instanceof Error?e.message:'Não foi possível atualizar seus dados.');}finally{setSaving(false)}}
 async function changePassword(){if(!token)return;if(password.length<8)return Alert.alert('Atenção','A nova senha deve ter pelo menos 8 caracteres.');if(password!==confirm)return Alert.alert('Atenção','A confirmação da nova senha não confere.');setChanging(true);try{await updatePassword(token,{current_password:current,password,password_confirmation:confirm});setCurrent('');setPassword('');setConfirm('');toast.success('Senha alterada com sucesso.');}catch(e){Alert.alert('Erro',e instanceof Error?e.message:'Não foi possível alterar a senha.');}finally{setChanging(false)}}
 return <SectionScreen title="Configurações" subtitle="Atualize seus dados pessoais e a segurança da conta." icon="settings-outline">
  <View style={s.card}><Header icon="person-outline" title="Dados da conta" text="Nome e sobrenome podem ser atualizados."/><Field label="Nome" value={name} onChangeText={setName}/><Field label="Sobrenome" value={lastName} onChangeText={setLastName}/><View style={{marginTop:13}}><Text style={s.label}>E-MAIL</Text><View style={s.locked}><Text style={s.lockedText}>{user?.email??'—'}</Text><Ionicons name="lock-closed" size={16} color="#64748B"/></View><Text style={s.help}>O e-mail da conta não pode ser alterado.</Text></View><Pressable disabled={saving} onPress={()=>void saveProfile()} style={s.primary}>{saving?<ActivityIndicator color="#FFF"/>:<><Ionicons name="save-outline" size={18} color="#FFF"/><Text style={s.primaryText}>Salvar alterações</Text></>}</Pressable></View>
  <View style={s.card}><Header icon="key-outline" title="Alterar senha" text="Confirme sua senha atual antes de definir uma nova."/><Field secure label="Senha atual" value={current} onChangeText={setCurrent}/><Field secure label="Nova senha" value={password} onChangeText={setPassword}/><Field secure label="Confirmar nova senha" value={confirm} onChangeText={setConfirm}/><Text style={s.help}>Use pelo menos 8 caracteres, com letras e números.</Text><Pressable disabled={changing} onPress={()=>void changePassword()} style={s.green}>{changing?<ActivityIndicator color="#0B1020"/>:<><Ionicons name="shield-checkmark-outline" size={18} color="#0B1020"/><Text style={s.greenText}>Alterar senha</Text></>}</Pressable></View>
 </SectionScreen>;
}
function Header({icon,title,text}:{icon:keyof typeof Ionicons.glyphMap;title:string;text:string}){return <View style={s.header}><View style={s.headerIcon}><Ionicons name={icon} size={20} color="#9B84FF"/></View><View style={{flex:1}}><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{text}</Text></View></View>}
function Field({label,value,onChangeText,secure=false}:{label:string;value:string;onChangeText:(v:string)=>void;secure?:boolean}){return <View style={{marginTop:13}}><Text style={s.label}>{label.toUpperCase()}</Text><TextInput value={value} onChangeText={onChangeText} secureTextEntry={secure} autoCapitalize={secure?'none':'words'} style={s.input} placeholderTextColor="#475569"/></View>}
const s=StyleSheet.create({card:{borderWidth:1,borderColor:'#1E293B',backgroundColor:'#161C2D',borderRadius:20,padding:18,marginBottom:14},header:{flexDirection:'row',gap:11,alignItems:'center',marginBottom:4},headerIcon:{width:40,height:40,borderRadius:12,backgroundColor:'rgba(109,74,255,.12)',alignItems:'center',justifyContent:'center'},title:{color:'#F8FAFC',fontSize:16,fontWeight:'900'},subtitle:{color:'#94A3B8',fontSize:11,marginTop:3},label:{color:'#64748B',fontSize:9,fontWeight:'900',letterSpacing:1},input:{marginTop:7,minHeight:48,borderWidth:1,borderColor:'#334155',backgroundColor:'#0B1020',borderRadius:13,paddingHorizontal:14,color:'#F8FAFC',fontSize:14},locked:{marginTop:7,minHeight:48,borderWidth:1,borderColor:'#1E293B',backgroundColor:'rgba(11,16,32,.65)',borderRadius:13,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},lockedText:{color:'#64748B',fontSize:14},help:{color:'#64748B',fontSize:10,lineHeight:16,marginTop:7},primary:{minHeight:49,borderRadius:13,backgroundColor:'#6D4AFF',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:18},primaryText:{color:'#FFF',fontWeight:'900'},green:{minHeight:49,borderRadius:13,backgroundColor:'#15D0A5',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:18},greenText:{color:'#0B1020',fontWeight:'900'}})
